export default [
  {
    id: "-MQjX4RIuYsTsJ68fb0w",
    aps1: 1,
    aps2: 1,
    codigodisciplina: "EADREL",
    cursos: "EF",
    disciplina: "A RECREAÇÃO E LAZER",
    gabaps1: 1,
    gabaps2: 1,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Thiago Azevedo",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RNnr9fdKptp5zL",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "ADCONF2",
    cursos: "CC",
    disciplina: "ANÁLISE DAS DEMONSTRAÇÕES CONTÁBEIS E FINANCEIRAS II",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Daniele Perissé",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4ROMSqcHdK8xpUX",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "ADMCONF",
    cursos: "RH, TEO",
    disciplina: "ADMINISTRAÇÃO DE CONFLITOS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Danielle Pussiareli",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4ROMSqcHdK8xpUY",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "ADVENEG",
    cursos: "ADM",
    disciplina: "ADMINISTRAÇÃO DE VENDA E NEGOCIAÇÕES",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Danielle Pussiareli",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RP_Kn1EzJkqLpt",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "ANCONEC",
    cursos: "CC",
    disciplina: "ANÁLISE DA CONJUNTURA ECONÔMICA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Alexandre Moreira Vieira",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RQ2T-B1p2ZZH92",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "ANTROPG",
    cursos: "ADM, CC, PED, GEO, HIST, TEO",
    disciplina: "ANTROPOLOGIA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Miriam Vieira",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RQ2T-B1p2ZZH93",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "ASCONTA",
    cursos: "CC",
    disciplina: "ANÁLISE DOS SISTEMAS CONTÁBEIS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Rosely Pereira",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RRTMUFM8zO27y8",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "AUCONT1",
    cursos: "CC",
    disciplina: "AUDITORIA CONTÁBIL I",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "sem nome",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RRTMUFM8zO27y9",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "CALCL00",
    cursos: "EC, EP",
    disciplina: "CÁLCULO",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Italo Coutinho",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RSnGo8BgjtH7LK",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "CALDFI2",
    cursos: "EC, EP",
    disciplina: "CÁLCULO DIFERENCIAL E INTEGRAL II",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Jorge Mattos",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RTsWu4Mgzu_Zwj",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "COARMA1",
    cursos: "EC",
    disciplina: "CONCRETO ARMADO I",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Artur Almeida Tavares",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RTsWu4Mgzu_Zwk",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "COARMA3",
    cursos: "EC",
    disciplina: "CONCRETO ARMADO II",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Artur Almeida Tavares",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RU78nYh1UkUXy4",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "COMEXTE",
    cursos: "ADM, CC",
    disciplina: "COMÉRCIO EXTERIOR - JA NO CANVAS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Simone Monteiro",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RU78nYh1UkUXy5",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "COMORGA",
    cursos: "ADM, RH",
    disciplina: "COMUNICAÇÃO ORGANIZACIONAL",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Danielle Pussiareli",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RVnGI1i67TA8Xv",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "COMPHUO",
    cursos: "ADM, RH",
    disciplina: "COMPORTAMENTO HUMANO NAS ORGANIZAÇÕES",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Dura Ferrer",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RWfJqGFqVJ0onS",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "CONAGPE",
    cursos: "CC",
    disciplina: "CONTABILIDADE AGRÍCOLA E PECUÁRIA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "sem nome",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RYwdgimn-Yd6z8",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "CONBASE",
    cursos: "ADM",
    disciplina: "CONTABILIDADE BÁSICA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Rosely Pereira",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RZD1nkmXC0joUr",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "CONCUT1",
    cursos: "ADM, CC",
    disciplina: "CONTABILIDADE DE CUSTOS I",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Luiz Américo",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4Rb3Ssr0BkyZFdS",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "CONGERE",
    cursos: "EP, ADM",
    disciplina: "CONTABILIDADE GERENCIAL",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Daniele Perissé",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RcMaQ7fy_TxlFj",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "COSOCI1",
    cursos: "CC",
    disciplina: "CONTABILIDADE SOCIETÁRIA I",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "sem nome",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RcMaQ7fy_TxlFk",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "CPGOVER",
    cursos: "CC",
    disciplina: "CONTABILIDADE PÚBLICA E GOVERNAMENTAL",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "sem nome",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RdUy-5BGO_KOTa",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "CTRIBUT",
    cursos: "CC",
    disciplina: "CONTABILIDADE TRIBUTÁRIA I",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Daniele Perissé",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RdUy-5BGO_KOTb",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "CUSTOIN",
    cursos: "EP",
    disciplina: "CUSTOS INDUSTRIAIS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Adriano Serra Silvério",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4ReOgK3SLeqHXic",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "DEPRENC",
    cursos: "EC",
    disciplina: "DESENHO DE PROJETO DE ENGENHARIA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Rômulo Coelho",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4ReOgK3SLeqHXid",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "DHBRASI",
    cursos: "institucional",
    disciplina: "DIREITOS HUMANOS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Maria Luiza Carvalhido",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4ReOgK3SLeqHXie",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "DITRPRE",
    cursos: "ADM, CC, RH",
    disciplina: "DIREITO DO TRABALHO E PREVIDENCIÁRIO I",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Maria Luiza Carvalhido",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RfZi2B479bG9Ks",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "DTECNIC",
    cursos: "EC, EP",
    disciplina: "DESENHO TÉCNICO",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Carlos Eduardo Cunha Martins",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RfZi2B479bG9Kt",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "DTRIBU2",
    cursos: "CC",
    disciplina: "DIREITO TRIBUTÁRIO II",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Maria Luiza Carvalhido",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RgDl5iZdv5dySx",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADADCS",
    cursos: "RH",
    disciplina: "ADMINISTRAÇÃO DE CARGOS E SALÁRIOS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Fabiano",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RgDl5iZdv5dySy",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADAED1",
    cursos: "LET, PED, GEO, HIST, BIO",
    disciplina: "AVALIAÇÃO NA EDUCAÇÃO I - JA NO CANVAS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Alexsandro Rosa Soares",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RhEzR5gUgJ7nFu",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADAED2",
    cursos: "LET, PED, GEO, HIS, BIO",
    disciplina: "AVALIAÇÃO NA EDUCAÇÃO II",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Alexsandro Rosa Soares",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RhEzR5gUgJ7nFv",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADAEDU",
    cursos: "PED",
    disciplina: "ARTE E EDUCAÇÃO - MUSICALIZAÇÃO / ARTES CÊNICAS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Thiago Mota",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RigNwy1s-Pxmc8",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADALLE",
    cursos: "PED",
    disciplina: "ALFABETIZAÇÃO E LETRAMENTO",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Thiago Mota",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4Rjw5j_DcujB27W",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADANA1",
    cursos: "EF",
    disciplina: "ANATOMIA 1",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Douglas Alves Ferreira",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4Rjw5j_DcujB27X",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADANTT",
    cursos: "TEO",
    disciplina: "ANTIGO TESTAMENTO E TBVT",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Valtair Miranda",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RkMTsIspTpYJ9Z",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADAVMO",
    cursos: "EF",
    disciplina: "AVALIAÇÃO MORFOFUNCIONAL",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "sem nome",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RkMTsIspTpYJ9_",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADBIOE",
    cursos: "EF",
    disciplina: "BIOESTATÍSTICA - JA NO CANVAS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Jorge Mattos",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RkMTsIspTpYJ9a",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADCAR2",
    cursos: "GEO",
    disciplina: "CARTOGRAFIA II",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Lívia Silva de Carvalho",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RlD6XeC8TeTBkD",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADCIHE",
    cursos: "EF",
    disciplina: "CITOLOGIA, HISTOLOGIA E EMBRIOLOGIA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Livia Palma",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RlD6XeC8TeTBkE",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADCLI2",
    cursos: "GEO",
    disciplina: "CLIMATOLOGIA II - JA NO CANVAS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Marlúcia zanon",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RmobHHkwpeBKnc",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADCULI",
    cursos: "TEO",
    disciplina: "CULTO E LITURGIA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "sem nome",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RmobHHkwpeBKnd",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADDEIN",
    cursos: "EF, PED",
    disciplina: "DESENVOLVIMENTO INFANTIL",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Carolina carmo",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RnEWQr4Lfj4ZBU",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADDID1",
    cursos: "LET,GEO, HIST, PED, BIO",
    disciplina: "DIDÁTICA I",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Miriam Vieira",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RoPoiCTHliEFKJ",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADDID2",
    cursos: "LET,GEO, HIST, PED, BIO",
    disciplina: "DIDÁTICA II",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Alexsandro Rosa",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RoPoiCTHliEFKK",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADEDET",
    cursos: "PED, HIS, GEO",
    disciplina: "EDUCAÇÃO E ÉTICA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Alexsandro Rosa Soares",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4Rp_3TaqpXj_Bpw",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADEDFD",
    cursos: "EF",
    disciplina: "DIDÁTICA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Douglas Doop",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RqZ_b2abMiDt6L",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADEDI1",
    cursos: "LET, PED, GEO, BIO",
    disciplina: "EDUCAÇÃO INCLUSIVA I",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Carolina Carmo",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RrjH86_Dq4GCQQ",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADEDI2",
    cursos: "PED, GEO, HIS, BIO",
    disciplina: "EDUCAÇÃO INCLUSIVA II - JA NO CANVAS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Carolina Carmo",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4Rs3A7VtI-hdeFT",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADEDJA",
    cursos: "PED",
    disciplina: "EDUCAÇÃO DE JOVENS E ADULTOS - JA NO CANVAS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Thiago Mota",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RtImcr6vmGoxHG",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADELTC",
    cursos: "LET",
    disciplina: "ESTUDOS LITERÁRIOS: TEORIA E CRÍTICA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Renato Resgala",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RunUc2BlOz6oGT",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADESCA",
    cursos: "TEO",
    disciplina: "ESCATOLOGIA - NÃO TEM VIDEOAULAS DA BLACKBOARD",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Niander Cerqueira",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RvOl0yn5qPkXem",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADFPCI",
    cursos: "PED, GEO, HIST, TEO",
    disciplina: "FUNDAMENTOS DA PSICOLOGIA CIENTÍFICA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Denise Mello",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RvOl0yn5qPkXen",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADFUGR",
    cursos: "TEO, LET",
    disciplina: "FUNDAMENTOS DA GRAMÁTICA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Lenise Dutra",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RwtmDPsVVL0Wm_",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADGCOR",
    cursos: "RH",
    disciplina: "GESTÃO DE CLIMA ORGANIZACIONAL",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Renata Caveari",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RwtmDPsVVL0Wma",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADGDLI",
    cursos: "RH",
    disciplina: "GESTÃO DE DESEMPENHO E LIDERANÇA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Simone Monteiro",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RxiOWz6C5nlcMd",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADGECI",
    cursos: "GEO",
    disciplina: "GEOGRAFIA E CIBERESPAÇO",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Marlúcia zanon",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RyKSJueofeTVKW",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADGEOR",
    cursos: "RH, ADM, EP",
    disciplina: "GESTÃO ORGANIZACIONAL",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Alécio alvico teixeira Junior",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RyKSJueofeTVKX",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADGEPO",
    cursos: "GEO",
    disciplina: "GEOGRAFIA POLÍTICA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Miriam Vieira",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RzQVailZ8OQ7Fw",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADGRE2",
    cursos: "TEO",
    disciplina: "GREGO II",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Ronaldo G. de Souza",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4RzQVailZ8OQ7Fx",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADGRIN",
    cursos: "GEO",
    disciplina: "GEOPOLÍTICA, REGIONALIZAÇÃO E INTEGRAÇÃO",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Josué Fortinni",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4S-lmZcowovLhZF",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADHAM2",
    cursos: "HIS",
    disciplina: "HISTÓRIA DA AMÉRICA II",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Savio Tomassini",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4S-lmZcowovLhZG",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADHERM",
    cursos: "TEO",
    disciplina: "HERMENÊUTICA I",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Valtair Miranda",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4S0_mKCcae3SSSe",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADHIB2",
    cursos: "HIS",
    disciplina: "HISTÓRIA DO BRASIL II",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Elaine Borges Sueth",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4S1A41WpU8N1FZI",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADHIB4",
    cursos: "HIS",
    disciplina: "HISTÓRIA DO BRASIL IV",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Elaine Borges Sueth",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4S2-WIwsJY8_clO",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADHICB",
    cursos: "TEO",
    disciplina: "HISTÓRIA DO CRISTIANISMO NO BRASIL (ESTÁ SEM O BRASIL)",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "sem nome",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4S32_3enoZVaWpZ",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADHIED",
    cursos: "PED, GEO, HIST, BIO",
    disciplina: "HISTÓRIA DA EDUCAÇÃO",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Miriam Vieira",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4S32_3enoZVaWp_",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADHIM2",
    cursos: "HIS",
    disciplina: "HISTÓRIA MEDIEVAL II",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Savio Tomassini",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4S47Y4N8UFFA-mU",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADHIRE",
    cursos: "HIS",
    disciplina: "HISTÓRIA REGIONAL",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Renata de Souza Silva",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4S5tgV6iYwav_kz",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADHIST",
    cursos: "HIS",
    disciplina: "HISTORIOGRAFIA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Savio Tomassini",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4S5tgV6iYwav_l-",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADHLPO",
    cursos: "LET",
    disciplina: "HISTÓRIA DA LÍNGUA PORTUGUESA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Lenise Dutra",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4S5tgV6iYwav_l0",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADHPPR",
    cursos: "TEO",
    disciplina: "HOMILÉTICA E PORTUGUÊS NA PREGAÇÃO",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Niander Cerqueira",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4S7bURvdSyyLkqR",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADINBI",
    cursos: "TEO",
    disciplina: "INTRODUÇÃO BÍBLICA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Josélio Souza",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4S7bURvdSyyLkqS",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADINEF",
    cursos: "EF",
    disciplina: "INTRODUÇÃO A EDUCAÇÃO FÍSICA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Thiago Azevedo",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4S8xrpCmNvedERt",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADINEH",
    cursos: "HIS",
    disciplina: "INTRODUÇÃO AO ESTUDO DA HISTÓRIA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Renata de Souza Silva",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4S9j8ZiulvyEuvs",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADINTG",
    cursos: "GEO",
    disciplina: "INTRODUÇÃO A GEOGRAFIA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Josué Fortinni",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SApHNY0NAy-Vtx",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADLIAP",
    cursos: "LET",
    disciplina: "LINGUÍSTICA APLICADA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Frederico Ludugério",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SApHNY0NAy-Vty",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADLIBR",
    cursos: "LET",
    disciplina: "LITERATURA BRASILEIRA - TRADIÇÃO",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Renato Resgala",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SBKUxgSFVrSuC8",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADLIGE",
    cursos: "LET",
    disciplina: "LINGUÍSTICA GERAL",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Frederico Ludugério",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SBKUxgSFVrSuC9",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADMEBA",
    cursos: "EF",
    disciplina: "METODOLOGIA DO ENSINO DO BASQUETEBOL",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "sem nome",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SCc11Q6EmOoUtf",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADMEEF",
    cursos: "EF",
    disciplina: "METODOLOGIA DO ENSINO DO FUTEBOL",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Thiago Azevedo",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SCc11Q6EmOoUtg",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADMEMU",
    cursos: "EF",
    disciplina: "METODOLOGIA DA MUSCULAÇÃO",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "sem nome",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SD2fMoHnMUfbDc",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADMEVO",
    cursos: "EF",
    disciplina: "METODOLOGIA DO ENSINO DO VOLEIBOL - JA NO CANVAS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Thiago Azevedo",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SD2fMoHnMUfbDd",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADMLP2",
    cursos: "LET",
    disciplina: "MORFOLOGIA DA LÍNGUA PORTUGUESA II",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Lenise Dutra",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SD2fMoHnMUfbDe",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADMPCH",
    cursos: "TEO",
    disciplina: "MÉTODOS E TEC.DE PESQ.EM C.SOCIAIS E HUMANAS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "sem nome",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SEcHHTYw1gOTTx",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADMPEL",
    cursos: "PED",
    disciplina: "METODOLOGIA E PRÁTICA DE ENSINO DE LÍNGUA PORTUGUESA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Lenise Dutra",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SEcHHTYw1gOTTy",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADMPHG",
    cursos: "PED",
    disciplina: "METODOLOGIA E PRÁTICA NO ENSINO DE HISTÓRIA E GEOGRAFIA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Elaine Borges Sueth",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SEcHHTYw1gOTTz",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADNEUR",
    cursos: "EF",
    disciplina: "NEUROFISIOLOGIA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Douglas Alves Ferreira",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SFGHujFhNzGKEB",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADPPG1",
    cursos: "LET, PED, GEO, HIST, BIO",
    disciplina: "POLÍTICAS PÚBLICAS E GESTÃO EDUCACIONAL I - JA NO CANVAS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Miriam Vieira",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SFGHujFhNzGKEC",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADPRP1",
    cursos: "LET, PED, GEO, HIST, BIO",
    disciplina: "PRÁTICA PEDAGÓGICA I",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Liliane Cunha",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SFGHujFhNzGKED",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADPRP3",
    cursos: "LET, PED, GEO, HIST, BIO",
    disciplina: "PRÁTICA PEDAGÓGICA III - JA NO CANVAS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Liliane Cunha",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SGXNmjDA5yrBrS",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADPSOR",
    cursos: "RH",
    disciplina: "PSICOLOGIA ORGANIZACIONAL",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Renata Caveari",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SGXNmjDA5yrBrT",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADPTEL",
    cursos: "LET",
    disciplina: "PERSPECTIVA TEÓRICAS DA ESCRITA E DA LEITURA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Renato Resgala",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SGXNmjDA5yrBrU",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADQVTR",
    cursos: "RH",
    disciplina: "QUALIDADE DE VIDA NO TRABALHO",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Thiara Mourão",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SGXNmjDA5yrBrV",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADRIGR",
    cursos: "PED, HIS",
    disciplina: "RELAÇÕES INTERPESSOAIS E GRUPAIS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Dura Ferrer",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SHfqXTDCs9b0ba",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADSAME",
    cursos: "EF",
    disciplina: "SAÚDE MENTAL",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Annabelle Vargas",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SHfqXTDCs9b0bb",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADSAUC",
    cursos: "EF",
    disciplina: "SAÚDE COLETIVA - JA NO CANVAS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Annabelle Vargas",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SKzXq9gP3w6Qxy",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADTAC1",
    cursos: "TEO",
    disciplina: "TÉCNICAS DE ACONSELHAMENTO I - JA NO CANVAS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Josélio Gomes",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SL_YVwaRS8lG05",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADTECI",
    cursos: "LET, PED, GEO, HIST",
    disciplina: "TECNOLOGIA DA INFORMAÇÃO",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Jamil Bussade",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SL_YVwaRS8lG06",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADTECU",
    cursos: "PED",
    disciplina: "TEORIA DO CURRÍCULO",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Elaine Borges Sueth",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SN-r4oq8KfPdCL",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADTEPA",
    cursos: "TEO",
    disciplina: "TEOLOGIA PASTORAL",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Niander Cerqueira",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SN-r4oq8KfPdCM",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADTES3",
    cursos: "TEO",
    disciplina: "TEOLOGIA SISTEMÁTICA III",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Valtair Miranda",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SOlVeW1S_a1jLJ",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADTESI",
    cursos: "TEO",
    disciplina: "TEOLOGIA SISTEMÁTICA I",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Valtair Miranda",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SPzeZWykNJqkgP",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EADTRDE",
    cursos: "RH",
    disciplina: "TREINAMENTO E DESENVOLVIMENTO",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Fabiano",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SPzeZWykNJqkgQ",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EDIFICS",
    cursos: "EC",
    disciplina: "EDIFICAÇÕES",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Gabriel Pereira Gonçalves",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SQjT2eykXY2rcy",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EDUAMBI",
    cursos: "institucional",
    disciplina: "EDUCAÇÃO AMBIENTAL - JA NO CANVAS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Marcos Paulo Thomé",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SQjT2eykXY2rcz",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EMPREEN",
    cursos: "ADM, CC, RH",
    disciplina: "EMPREENDEDORISMO",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Frederico Margem",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SRclHs5cAznueG",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EMPRINO",
    cursos: "ADM, CC, RH, EP",
    disciplina: "EMPREENDEDORISMO E INOVAÇÃO",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Frederico Margem",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SRclHs5cAznueH",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "ENMETOD",
    cursos: "EP",
    disciplina: "ENGENHARIA DE MÉTODOS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Ana Karina Mendonça",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SShTVqGc72sB5A",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "ENSEGTR",
    cursos: "EC, EP",
    disciplina: "ENGENHARIA DE SEGURANÇA DO TRABALHO",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Henrique medeiros",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SShTVqGc72sB5B",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "ERB99",
    cursos: "institucional",
    disciplina: "ESTUDO DAS RELAÇÕES ÉTNICO RACIAIS NO BRASIL - JA NO CANVAS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Vinícius Mérida",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SShTVqGc72sB5C",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "ESTRAS1",
    cursos: "EC",
    disciplina: "ESTRADAS I",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Pietro Valdo Rostagno",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4STglqXDC8Fk1Af",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "ESUP1EX",
    cursos: "institucional",
    disciplina: "ESTÁGIO SUPERVISIONADO I - EXATAS - JA NO CANVAS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "sem nome",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SUx1c1sPhadDSx",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "ESUP1HU",
    cursos: "TEO",
    disciplina: "ESTÁGIO SUPERVISIONADO I- HUMANAS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "sem nome",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SUx1c1sPhadDSy",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "ESUP1LI",
    cursos: "LET, PED, GEO, HIST, BIO",
    disciplina: "ESTÁGIO SUPERVISIONADO I - LICENCIATURAS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Fabiana Costa Ramos",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SVdSERTO5WHGUV",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "ESUP2EX",
    cursos: "institucional",
    disciplina: "ESTÁGIO SUPERVISIONADO II",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "sem nome",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SWM7UNo32yPevp",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "ETICAPO",
    cursos: "institucional",
    disciplina: "ÉTICA - JA NO CANVAS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "ALEXSANDRO ROSA SOARES",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SWM7UNo32yPevq",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EXTINE1",
    cursos: "EC, EP",
    disciplina: "EXTENSÃO INTEGRADA EM EXATAS I",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Rômulo Coelho Delfino",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SWM7UNo32yPevr",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EXTINE3",
    cursos: "EC, EP",
    disciplina: "EXTENSÃO INTEGRADA EM EXATAS III",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Amanda Camerini",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SXMjj14vc_J0U8",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EXTINE5",
    cursos: "EC, EP",
    disciplina: "EXTENSÃO INTEGRADA EM EXATAS V",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Rômulo Coelho",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SXMjj14vc_J0U9",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EXTINE7",
    cursos: "EC, EP",
    disciplina: "EXTENSÃO INTEGRADA EM EXATAS VII",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Rômulo Coelho",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SYJAukNFcIkQXa",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EXTINH1",
    cursos: "ADM, CC, RH, TEO, EF",
    disciplina: "EXTENSÃO INTEGRADA EM HUMANAS I",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Danielle Pussiareli",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SZbx6cUTvooBv4",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EXTINH3",
    cursos: "ADM, CC, RH, TEO, EF",
    disciplina: "EXTENSÃO INTEGRADA EM HUMANAS III",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Danielle Pussiareli",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4S_WhtAIt_vVVH8",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EXTINH5",
    cursos: "ADM, CC, RH, TEO, EF",
    disciplina: "EXTENSÃO INTEGRADA EM HUMANAS V",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Daniele Perissé",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SbbfRogfGmYb3s",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EXTINH6",
    cursos: "ADM, CC, RH, TEO, EF",
    disciplina: "EXTENSÃO INTEGRADA EM HUMANAS VI",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Daniele Perissé",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SbbfRogfGmYb3t",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EXTINL1",
    cursos: "LET, PED, GEO, HIST",
    disciplina: "EXTENSÃO INTEGRADA EM LICENCIATURA I",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Lenise Dutra",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SdYHcqy192lY3V",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EXTINL3",
    cursos: "LET, PED, GEO, HIST",
    disciplina: "EXTENSÃO INTEGRADA EM LICENCIATURA III",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Alexsandro Rosa Soares",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4Sfp2LaALGST7hG",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "EXTINL5",
    cursos: "LET, PED, GEO, HIST",
    disciplina: "EXTENSÃO INTEGRADA EM LICENCIATURA V",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Alexsandro Rosa Soares",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4Sfp2LaALGST7hH",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "FGP99",
    cursos: "RH",
    disciplina: "GESTÃO DE RH EM MICRO E PEQUENAS EMPRESAS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Danielle Pussiareli",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4ShbjSJ2QPC4xzj",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "FIGEXP2",
    cursos: "EC, EP",
    disciplina: "FÍSICA GERAL E EXPERIMENTAL II",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Amanda Camerini",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SiaPJpuNZPU_Kp",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "FILOSOA",
    cursos: "ADM, RH, CC, GEO, HIST, LET, PED, TEO, BIO",
    disciplina: "FILOSOFIA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Luiz Paulo",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SiaPJpuNZPU_Kq",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "FISICQU",
    cursos: "EP",
    disciplina: "FÍSICO-QUÍMICA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Ludmilla Rangel",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SjGTQ7hjwV0bB3",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "FISIOLG",
    cursos: "EF",
    disciplina: "FISIOLOGIA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Ludmilla Rangel",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SkTFsQ7EOniWqv",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "FUARURB",
    cursos: "EC",
    disciplina: "FUNDAMENTOS DE ARQUITETURA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Jefferson Seufitteli",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SkTFsQ7EOniWqw",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "FUELETR",
    cursos: "EC, EP",
    disciplina: "FUNDAMENTOS DE ELETRICIDADE",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Frederico Margem",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SkTFsQ7EOniWqx",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "GANALIT",
    cursos: "EC, EP",
    disciplina: "GEOMETRIA ANALÍTICA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Jorge Mattos",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SlZ6Bvwj05IE_r",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "GDESCRI",
    cursos: "EC",
    disciplina: "GEOMETRIA DESCRITIVA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Jorge Mattos",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SlZ6Bvwj05IE_s",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "GEESTRA",
    cursos: "CC, EP, ADM",
    disciplina: "GESTÃO ESTRATÉGICA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Danielle Pussiarelli",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SlZ6Bvwj05IE_t",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "GEOLOGA",
    cursos: "EC",
    disciplina: "GEOLOGIA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Fernanda Rangel",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SmE9LHDDNhEu6p",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "GEQUALI",
    cursos: "EP",
    disciplina: "GESTÃO DA QUALIDADE",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Adriano Serra Silvério",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SmE9LHDDNhEu6q",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "GMARKE2",
    cursos: "ADM",
    disciplina: "GESTÃO DE MARKETING II",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Simone Monteiro",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SoCypJnp_pB8_w",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "GMATERI",
    cursos: "ADM",
    disciplina: "GESTÃO DE MATERIAIS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Adriano Serra",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SpTp8e4Hc5j6Z-",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "GPESSO1",
    cursos: "ADM, CC, RH",
    disciplina: "GESTÃO DE PESSOAS I",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Simone Monteiro",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4Sq55IFLqGYcPLG",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "GPESSO2",
    cursos: "ADM",
    disciplina: "GESTÃO DE PESSOAS II",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Simone Monteiro",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4Sq55IFLqGYcPLH",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "GPROCES",
    cursos: "ADM",
    disciplina: "GESTÃO DE PROCESSOS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Danielle Pussiareli",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SrY5sBSfECFRBs",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "HIDRMFL",
    cursos: "EC",
    disciplina: "HIDRÁULICA E MÁQUINAS DE FLUXO",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Gabriel P Gonçalves",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SrY5sBSfECFRBt",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "IENGCIV",
    cursos: "EC,EP",
    disciplina: "INTRODUÇÃO À ENGENHARIA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Fernanda Rangel",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SrY5sBSfECFRBu",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "INADMIN",
    cursos: "ADM",
    disciplina: "INTRODUÇÃO A ADMINISTRAÇÃO - JA NO CANVAS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Danielle Pussiarelli",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SssJTGC3oSLRFx",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "INECONM",
    cursos: "EP, ADM",
    disciplina: "INTRODUÇÃO À ECONOMIA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Luiz Fernando Magalhães",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SssJTGC3oSLRFy",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "INGLESI",
    cursos: "institucional",
    disciplina: "INGLÊS INSTRUMENTAL - JA NO CANVAS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Frederico Ludugiero",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SssJTGC3oSLRFz",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "INSTPEL",
    cursos: "EC",
    disciplina: "INSTALAÇÕES PREDIAIS ELÉTRICA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Afonso Rangel G. de Azevedo",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SssJTGC3oSLRG-",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "INTRCON",
    cursos: "CC",
    disciplina: "INTRODUÇÃO A CONTABILIDADE",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Daniele Perissé",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SssJTGC3oSLRG0",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "JOGEMPR",
    cursos: "ADM",
    disciplina: "JOGOS DE EMPRESAS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Danielle Pussiareli",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4Stc7O4JqFuJwA9",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "LIBRAAS",
    cursos: "institucional",
    disciplina: "LIBRAS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Carolina Carmo",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4Stc7O4JqFuJwAA",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "LOGISTC",
    cursos: "ADM, EP",
    disciplina: "LOGÍSTICA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Maykon de Souza Silva",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4Stc7O4JqFuJwAB",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "MACONS2",
    cursos: "EC",
    disciplina: "MATERIAIS DE CONSTRUÇÃO II - JA NO CANVAS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Gabriel Pereira Gonçalves",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SuvC_AMvOj3Ezj",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "MATBASI",
    cursos: "ADM, CC",
    disciplina: "MATEMÁTICA BÁSICA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Jorge Mattos",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SvAT0Fh8vQ7ioz",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "MATFINA",
    cursos: "EP, ADM",
    disciplina: "MATEMÁTICA FINANCEIRA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Italo Coutinho",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SvAT0Fh8vQ7ip-",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "MCIENTI",
    cursos: "EC, EP, RH, ADM, CC, EF, PED, LET, TEO, GEO, HIS",
    disciplina: "METODOLOGIA CIENTÍFICA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Cileny Saroba",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4SvAT0Fh8vQ7ip0",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "MECGERA",
    cursos: "EC, EP",
    disciplina: "MECÂNICA GERAL",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Gabriel Pereira Gonçalves",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4Sz1Mzo3mBPFhYO",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "MESOLO2",
    cursos: "EC",
    disciplina: "MECÂNICA DOS SOLOS II",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Walter Gualberto Martins",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4T-gJYIOTvrKvG0",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "NOCDIRE",
    cursos: "ADM, CC",
    disciplina: "NOÇÕES DE DIREITO",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Fernanda Acha",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4T-gJYIOTvrKvG1",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "OBRASHI",
    cursos: "EC",
    disciplina: "OBRAS HIDRÁULICAS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Pietro Valdo Rostagno",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4T-gJYIOTvrKvG2",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "ORCAMET",
    cursos: "ADM, CC",
    disciplina: "ORÇAMENTO I",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Alexandre Moreira",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4T-gJYIOTvrKvG3",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "PECONT1",
    cursos: "CC",
    disciplina: "PERÍCIA CONTÁBIL I",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Rosely Pereira",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4T002Tw5jUt-kV0",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "PEOPER2",
    cursos: "EP",
    disciplina: "PESQUISA OPERACIONAL II",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Raphael Ramos",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4T002Tw5jUt-kV1",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "PINSTRU",
    cursos: "TEO, PED, GEO, HIS",
    disciplina: "PORTUGUÊS INSTRUMENTAL",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Renato Resgala",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4T002Tw5jUt-kV2",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "PLCONPR",
    cursos: "EP",
    disciplina: "PLANEJAMENTO E CONTROLE DA PRODUÇÃO",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Frederico Margem",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4T1O2PKctRPDmyT",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "PLNEGOC",
    cursos: "ADM, EP",
    disciplina: "PLANO DE NEGÓCIOS - JA NO CANVAS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Alécio alvico teixeira Junior",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4T1O2PKctRPDmyU",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "PONTESS",
    cursos: "EC",
    disciplina: "PONTES",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Artur Almeida Tavares",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4T1O2PKctRPDmyV",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "POPERA1",
    cursos: "EP",
    disciplina: "PESQUISA OPERACIONAL I",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Raphael Ramos",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4T1O2PKctRPDmyW",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "PRCIMAT",
    cursos: "EC, EP",
    disciplina: "PRINCIPIO DE CIÊNCIAS DOS MATERIAIS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Valtency Ferreira",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4T1O2PKctRPDmyX",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "PROJEPR",
    cursos: "EP",
    disciplina: "PROJETO DE PRODUTO",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Maykon de Souza Silva",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4T2r9GzWQnlpb0l",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "PRPLCPR",
    cursos: "EP",
    disciplina: "PROGRAMAÇÃO,PLANEJAMENTO E CONTROLE DA PRODUÇÃO",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Frederico Margem",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4T2r9GzWQnlpb0m",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "QUGERAL",
    cursos: "EC, EP",
    disciplina: "QUÍMICA GERAL",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Valtency Ferreira",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4T2r9GzWQnlpb0n",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "REMATE1",
    cursos: "EC, EP",
    disciplina: "RESISTÊNCIA DOS MATERIAIS I",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Muriel Oliveira",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4T2r9GzWQnlpb0o",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "SISTHI2",
    cursos: "EC",
    disciplina: "SISTEMAS HIPERESTÁTICOS II",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Rômulo Coelho Delfino",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4T3-F2Y-xJGkLvs",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "SOCIOLI",
    cursos: "ADM, CC, RH, GEO, HIST, TEO, PED, BIO",
    disciplina: "SOCIOLOGIA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Annabelle",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4T3-F2Y-xJGkLvt",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "SUSOAMB",
    cursos: "EC, EP, ADM, CC, RH",
    disciplina: "SUSTENTABILIDADE SÓCIOAMBIENTAL",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Cileny Saroba",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4T3-F2Y-xJGkLvu",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "TCC1EXA",
    cursos: "EC, EP",
    disciplina: "TRABALHO DE CONCLUSÃO DE CURSO I - EXATAS - JA NO CANVAS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Amanda Camerini",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4T3-F2Y-xJGkLvv",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "TCC1HUM",
    cursos: "TEO",
    disciplina: "TRABALHO DE CONCLUSÃO DE CURSO I- HUMANAS - JA NO CANVAS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Renato Resgala",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4T4wV1RU3LnMkSt",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "TCC2EXA",
    cursos: "EC, EP",
    disciplina: "TRABALHO DE CONCLUSÃO DE CURSO II - EXATAS - JA NO CANVAS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Amanda Camerini",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4T4wV1RU3LnMkSu",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "TCCREHU",
    cursos: "RH",
    disciplina: "TRABALHO DE CONCLUSÃO DE CURSO - JA NO CANVAS",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Danielle Pussiareli",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4T4wV1RU3LnMkSv",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "TEGEADM",
    cursos: "EP, RH, ADM, CC",
    disciplina: "TEORIA GERAL DA ADMINISTRAÇÃO",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Ana Karina Mendonça",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4T4wV1RU3LnMkSw",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "TMACECO",
    cursos: "ADM, CC",
    disciplina: "TEORIA MACRO ECONÔMICA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Luiz Fernando Magalhães",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4T4wV1RU3LnMkSx",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "TMICECO",
    cursos: "ADM, CC",
    disciplina: "TEORIA MICRO ECONÔMICA",
    gabaps1: 2,
    gabaps2: 2,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Luiz Magalhães",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  },
  {
    id: "-MQjX4T5mTdmDinxXyQ7",
    aps1: 2,
    aps2: 2,
    codigodisciplina: "TOPOBAS",
    cursos: "EC",
    disciplina: "TOPOGRAFIA BÁSICA",
    gabaps1: 1,
    gabaps2: 1,
    gabma1: 2,
    gabma2: 2,
    horarioatendimento: ["TESTE"],
    inspirese: 2,
    livros: 2,
    ma1: 2,
    ma2: 2,
    nameprofessor: "Pietro Valdo Rostagno",
    pea: 2,
    periodo: "2021-1",
    situacao: 1,
    videoaulas: 2
  }
]